openapi: 3.0.0
info:
  title: E-commerce API
  version: 1.0.0
paths:
  /api/customers:
    post:
      summary: Create a customer
      responses:
        201:
          description: Customer created
  /api/customers/{customer_id}:
    get:
      summary: Get customer details
      responses:
        200:
          description: Customer details
    put:
      summary: Update customer details
      responses:
        200:
          description: Customer updated
    delete:
      summary: Delete a customer
      responses:
        204:
          description: Customer deleted
# Add additional paths for orders and products
