openapi: 3.0.0
info:
  title: Customer and Product API
  description: API documentation for managing customers, products, and orders.
  version: 1.0.0
paths:
  /api/customers:
    post:
      summary: Create a new customer
      responses:
        '201':
          description: Customer created
  /api/customers/{id}:
    get:
      summary: Get a customer by ID
      responses:
        '200':
          description: Customer details
    put:
      summary: Update a customer
      responses:
        '200':
          description: Customer updated
    delete:
      summary: Delete a customer
      responses:
        '204':
          description: Customer deleted
  /api/products:
    post:
      summary: Create a new product
      responses:
        '201':
          description: Product created
  /api/products/{id}:
    get:
      summary: Get a product by ID
      responses:
        '200':
          description: Product details
    put:
      summary: Update a product
      responses:
        '200':
          description: Product updated
    delete:
      summary: Delete a product
      responses:
        '204':
          description: Product deleted
  /api/orders:
    post:
      summary: Place a new order
      responses:
        '201':
          description: Order created
  /api/orders/{id}:
    get:
      summary: Get an order by ID
      responses:
        '200':
          description: Order details
